### ISSUE TITLE
facing issue to insert data into data base it save nothing just empty spaces

### ISSUE THREAD

**Issue by amirgee007** [thomasjbradley/saving-signatures-sample#3]
i have used this app in my project but it gives me error message in console how to minimise it.

here to go 
![scracterror](https://cloud.githubusercontent.com/assets/16411441/24495977/5ea7231a-1550-11e7-9daf-f5792fb2841d.JPG)

**Comment by thomasjbradley** [comment]
Looks like a couple files aren’t connected. Did you download signature pad and put it's files in?

**Comment by amirgee007** [comment]
yes i download and its connected but is giving me issue to save data un db let me add files here

**Comment by amirgee007** [comment]
https://www.dropbox.com/s/ntb22uqn8hrsngq/sample-signature-output.zip?dl=0

**Comment by amirgee007** [comment]
here are the files please take a look I know your time is precious but i have tried many times but didn't get the point to fix it.

thanks for your time

**Comment by thomasjbradley** [comment]
Seems to work okay to me. I downloaded your code an loaded it with a PHP server and I'm able to sign the signature pad.

Are you still unable to sign with signature pad?

**Comment by amirgee007** [comment]
yes bro is working now thanks for your time i was not adding all the require files in the projects. thanks man you are great <3 

thanks for your time
